apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: carts-hpa
  namespace: default
  labels:
    app.kubernetes.io/name: carts
    app.kubernetes.io/instance: carts
    app.kubernetes.io/component: autoscaling
    app.kubernetes.io/owner: retail-store-sample

spec:
  scaleTargetRef:
    kind: Deployment
    name: carts
    apiVersion: apps/v1
  minReplicas: 3
  maxReplicas: 12

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70

    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - periodSeconds: 15
          type: Percent
          value: 50

        - type: Pods
          value: 1
          periodSeconds: 60
      selectPolicy: Min

    scaleUp:
      policies:
        - periodSeconds: 15
          type: Percent
          value: 100
        
        - type: Pods
          value: 1
          periodSeconds: 15
      selectPolicy: Max
    