apiVersion: v1
kind: Secret
metadata:
  name: mysecret-mysql
type: Opaque
data:
  RETAIL_CATALOG_PERSISTENCE_USER: Y2F0YWxvZ191c2Vy
  RETAIL_CATALOG_PERSISTENCE_PASSWORD: QmhhdmluQDEyMw==
  RETAIL_CATALOG_PERSISTENCE_ENDPOINT: "Y2F0YWxvZy1teXNxbC0wLmNhdGFsb2ctbXlzcWwuZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2NhbA=="
  RETAIL_CATALOG_PERSISTENCE_DB_NAME: "Y2F0YWxvZ2Ri"
