app:
  theme: teal # orange, green, default

# Ingress for ALB

ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/schema: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /actuator/health/liveness
  tls: []
  hosts: []

releaseInfo:
  enabled: true

image:
  repository: public.ecr.aws/aws-containers/retail-store-sample-ui
  pullPolicy: IfNotPresent
  tag: 1.3.0